### ISSUE TITLE
Missing hash key: "X-CSRF-TOKEN"

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#637]
After updating with commit 325e382c5bb2a77f76225b259594fc2575fab0be then booting my app, when I go to the home page, I get this `Missing hash key: "X-CSRF-TOKEN"` error.

Looking through these https://github.com/search?q=org%3Aluckyframework+session+csrf&type=Code
It looks like when calling `context.session.get("X-CSRF-TOKEN")` if that key isn't there, an exception is thrown vs using `session.get?()` where it would just return nil.

cc. @edwardloveall

**Comment by edwardloveall** [comment]
Related convo in gitter: 
https://gitter.im/luckyframework/Lobby?at=5bc8c0adae7be940167a5747

**Comment by paulcsmith** [comment]
@jwoertink I think this should work now! If have issues with it though, feel free to reopen!

**Comment by jwoertink** [comment]
@paulcsmith I just pulled 0.12, and I still get this. A fresh lucky app doesn't have this same error. I even gave it a new session name just in case.

**Comment by jwoertink** [comment]
I should also add that it's tanking on this line https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/forgery_protection_helpers.cr#L23 My guess is I'm missing some include somewhere that gets added in during a new app. I'll try and dig through files of a new app to see if I can find the difference.

**Comment by paulcsmith** [comment]
@jwoertink Hmm, are you using the `form_for` helper? Is it happening on every request, or just POST?

**Comment by jwoertink** [comment]
I don't have any forms or POST. My app is all GET requests. This happens loading the home page

**Comment by paulcsmith** [comment]
Hmm...Could you post your src/app.cr? Maybe there is a missing handler or one is in the wrong order.

Also could you post `src/browser_action.cr`?

**Comment by jwoertink** [comment]
ah ha! I just checked, my BrowserAction needed `include Lucky::ProtectFromForgery`. I didn't think to check there. Adding that line in makes it work. That might need to go in those upgrade notes 👍  thanks! This issue can remain closed 😄

**Comment by ianpurton** [comment]
I'm getting a similar issue on a new lucky app.

```
 No key for 'X-CSRF-TOKEN' in session (Exception)
3:39:19 PM web.1    |    from lib/lucky/src/lucky/cookies/session.cr:42:18 in 'get'
3:39:19 PM web.1    |    from lib/lucky/src/lucky/protect_from_forgery.cr:12:5 in 'get_token'
3:39:19 PM web.1    |    from lib/lucky/src/lucky/tags/forgery_protection_helpers.cr:23:16 in 'csrf_meta_tags'
3:39:19 PM web.1    |    from src/components/shared/layout.cr:23:7 in 'shared_layout_head'
3:39:19 PM web.1    |    from src/pages/guest_layout.cr:11:19 in 'render'
3:39:19 PM web.1    |    from lib/lucky/src/lucky/html_builder.cr:57:5 in 'perform_render'
```

I have a home page which inherits from GuestLayout

This uses Shared::Layout.shared_layout_head 

```
class Home::IndexPage < GuestLayout
  def content
    h1 "Here"
  end
end
```

I think the issue is that shared_layout_head makes a call to csrf_meta_tags which expects the cookie to be set. So for example if I go to the /sign_in page it gets set and the home page works again.
